### ISSUE TITLE
Issue with vertical align that makes text blurry

### ISSUE THREAD

**Issue by siamkreative** [SiamKreative/SiamKreative-Studio#4]
``` css
.intro .wrapper-small {
    position: relative;
    top: 50%;
    transform: translateY(-50%);
}
```

Is causing the text to be blurry.
